WITH YOGURT AS (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'YOGURT'
), MILK AS (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'MILK'
)
SELECT DISTINCT(CART_ID)
FROM YOGURT JOIN MILK USING(CART_ID)
ORDER BY CART_ID