SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
WHERE I.ITEM_ID IN (
    SELECT T1.ITEM_ID
    FROM ITEM_TREE T1 left join ITEM_TREE T2 on T1.ITEM_ID = T2.PARENT_ITEM_ID
    WHERE T2.PARENT_ITEM_ID IS NULL AND T1.PARENT_ITEM_ID IS NOT NULL
    )
ORDER BY I.ITEM_ID DESC
