WITH B AS (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS AMOUNT
          FROM OFFLINE_SALE
          GROUP BY PRODUCT_ID)

SELECT PRODUCT_CODE, (P.PRICE * B.AMOUNT) AS SALES
FROM PRODUCT P JOIN B ON P.PRODUCT_ID = B.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE