SELECT APNT_NO, PT_NAME, P.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT A
JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
JOIN PATIENT P ON A.PT_NO = P.PT_NO
WHERE DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
AND A.MCDP_CD = 'CS'
AND A.APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD